import { GalleryMosaic } from "@/components/gallery/GalleryMosaic";
import type { GalleryItem } from "@/components/gallery/gallery-types";
import { MediaPlaceholder } from "@/components/media/MediaPlaceholder";
import { Section } from "@/components/ui/Section";
import { site } from "@/config/site";
import {
  getFolderMedia,
  imageSrcSet,
  imageUrl,
  isCloudinaryConfigured,
  videoPosterUrl,
  videoPreviewUrl,
  videoUrl,
} from "@/lib/cloudinary";

const THUMB_WIDTHS = [320, 480, 720, 960];
const FULL_WIDTH = 1600;

// How many tiles show before the see-all control. Set GALLERY_PREVIEW_COUNT to
// change it without touching the code.
function previewCount(): number {
  const raw = Number(process.env.GALLERY_PREVIEW_COUNT);
  return Number.isFinite(raw) && raw > 0 ? Math.floor(raw) : 10;
}

function runtime(seconds: number | null): string | null {
  if (seconds === null) {
    return null;
  }
  const total = Math.round(seconds);
  const minutes = Math.floor(total / 60);
  return `${minutes}:${String(total % 60).padStart(2, "0")}`;
}

// The gym's own photos and clips, newest first, so the grid reflects
// whatever was added most recently without anyone reordering anything.
export async function Gallery() {
  const assets = isCloudinaryConfigured() ? await getFolderMedia(site.media.galleryFolder) : [];

  const items: GalleryItem[] = assets.map((asset) => {
    const isVideo = asset.resourceType === "video";
    return {
      id: asset.publicId,
      kind: isVideo ? "video" : "image",
      // a video's thumbnail is a frame of the video, generated by Cloudinary
      thumb: isVideo ? videoPosterUrl(asset.publicId, 720) : imageUrl(asset.publicId, 720, 720),
      thumbSrcSet: isVideo ? "" : imageSrcSet(asset.publicId, THUMB_WIDTHS, 1),
      strip: isVideo ? videoPosterUrl(asset.publicId, 200) : imageUrl(asset.publicId, 200, 200),
      full: isVideo ? videoPosterUrl(asset.publicId, FULL_WIDTH) : imageUrl(asset.publicId, FULL_WIDTH),
      videoSrc: isVideo ? videoUrl(asset.publicId, FULL_WIDTH) : null,
      poster: isVideo ? videoPosterUrl(asset.publicId, FULL_WIDTH) : null,
      previewSrc: isVideo ? videoPreviewUrl(asset.publicId) : null,
      alt: asset.alt ?? asset.title ?? `${isVideo ? "Video" : "Photo"} from ${site.name}`,
      title: asset.title,
      caption: asset.caption,
      duration: runtime(asset.duration),
    };
  });

  return (
    <Section id="gallery" className="border-t border-border">
      <div className="stagger max-w-2xl">
        <p className="reveal type-eyebrow text-accent">Gallery</p>
        <h2 className="reveal mt-4 type-h2 text-ink">Inside the gym</h2>
        <p className="reveal mt-6 type-lead text-ink-muted">
          The floor, the kit and the people who train on it.
        </p>
      </div>

      <div className="mt-12">
        {items.length > 0 ? (
          <GalleryMosaic items={items} previewCount={previewCount()} />
        ) : (
          <MediaPlaceholder
            label={`Photos and videos appear here once they are uploaded to the "${site.media.galleryFolder}" folder in Cloudinary`}
            className="h-64 rounded-media"
          />
        )}
      </div>
    </Section>
  );
}
